let $CONFPATH='~/.vim/configurations/angular'
source ~/.vim/configurations/default/default.vim
source ~/.vim/configurations/code/code.vim
source ~/.vim/configurations/css/css.vim
source ~/.vim/configurations/html/html.vim
source ~/.vim/configurations/angular/angular.vim
